%%
clear;clc;

figure(1)
plot(total_util, toall_time_HFLSnF_fix,'-d',...
    total_util, toall_time_HFLSnF_los,'-s',...
    total_util, toall_time_FLSnF,'-x',...
    total_util, toall_time_FLnoSnF,'-o',...
    total_util, toall_time_HFLnoSnF_fix,'-hexagram',...
    total_util, toall_time_HFLnoSnF_los,'-v');
title('time');
xlabel('Utilization');
ylabel('total time');
legend('HFLSnF-fix','HFLSnF-adapt','FLSnF','FLnoSnF','HFLnoSnF-fix','HFLnoSnF-adapt',Location='best');
grid on;

figure(2)
plot(total_util, enum_HFLSnF_fix,'-d',...
    total_util, enum_HFLSnF_los,'-s',....
    total_util, enum_HFLnoSnF_fix,'-hexagram',...
    total_util, enum_HFLnoSnF_los,'-v');
title('group num')
xlabel('Utilization');
ylabel('number');
legend('HFLSnF-fix','HFLSnF-adapt','HFLnoSnF-fix','HFLnoSnF-adapt');
grid on;

figure(3)
plot(total_util, cnum_HFLSnF_fix,'-d',...
    total_util, cnum_HFLSnF_los,'-s',...
    total_util, cnum_FLSnF,'-x',...
    total_util, cnum_FLnoSnF,'-o',...
    total_util, cnum_HFLnoSnF_fix,'-hexagram',...
    total_util, cnum_HFLnoSnF_los,'-v');
title('Client Number')
xlabel('Utilization');
ylabel('number');
legend('HFLSnF-fix','HFLSnF-adapt','FLSnF','FLnoSnF','HFLnoSnF-fix','HFLnoSnF-adapt',Location='best');
grid on;

% figure(4)
% plot(total_util, aver_time_agg_HFLSnF_fix,'-d',...
%     total_util, aver_time_agg_HFLSnF_los,'-s',...
%     total_util, aver_time_agg_FLSnF,'-x',...
%     total_util, aver_time_agg_FLnoSnF,'-o',...
%     total_util, aver_time_agg_HFLnoSnF_fix,'-hexagram',...
%     total_util, aver_time_agg_HFLnoSnF_los,'-v');
% title('Time of Aggregating')
% xlabel('Utilization');
% ylabel('Time of Aggregating ');
% legend('HFLSnF-fix','HFLSnF-adapt','FLSnF','FLnoSnF','HFLnoSnF-fix','HFLnoSnF-adapt',Location='best');
% grid on;

toc;
